from classification import normalize_configuration

GROUP_NAMES = {
    1: "AD_FLUIDEZ",
    2: "FILLERS",
    3: "AD_SECAN",
    4: "AD_DESMO",
    5: "FV",
    6: "PE_ADCOPO",
    7: "PE_ADHOMO",
    8: "PE_ADHOMO",
    9: "PE_LINEAL",
    10: "PP_COIM",
    11: "PP_CONBRE",
    12: "PP_CORCLA",
    13: "PPHOMO_COPO",
    14: "TPE",
    15: "PP_HOMO",
    16: "PP_HOMO",
    17: "CO_MB",
}

UNCLASSIFIED_KEY = 0
UNCLASSIFIED = "SIN CLASIFICAR"
EXCLUDED = "no"

RAW_ITEM_GROUP_MAP = {
    ("AD", "N"): 4,
    ("AD", "VIRGEN"): 4,
    ("AD001", "DESMOLDANTESTK11"): 4,
    ("AD001", "DESMOLDANTESTK251"): 4,
    ("AD001", "POLIBACH"): 4,
    ("AD001", "SECANTE"): 3,
    ("AD004", "NA"): 4,
    ("AD_ANTIEST", "VIRGEN"): 4,
    ("AD_AYUDA", "VIRGEN"): 4,
    ("AD_DESMO", "VIRGEN"): 4,
    ("AD_ESTAB", "VIRGEN"): 4,
    ("AD_FLUIDEZ", "VIRGEN"): 1,
    ("AD_SECAN", "VIRGEN"): 3,
    ("AD_SULFATO", "VIRGEN"): 2,
    ("AD_UV", "VIRGEN"): 4,
    ("CC", "VIRGEN"): 17,
    ("CO", "GRA"): "no",
    ("CO", "N"): "no",
    ("CO", "PEARL"): "no",
    ("CO", "TR"): "no",
    ("CO001", "CORESA"): "no",
    ("CO001", "NA"): "no",
    ("CO001", "POLYCOLOR"): "no",
    ("CO001", "TOSAF"): "no",
    ("CO002", None): "no",
    ("CO_MB", "VIRGEN"): "no",
    ("CO_MB_TEST", "VIRGEN"): "no",
    ("ColadaPP", None): 16,
    ("ELASTOMERO", "NA"): 14,
    ("FIBRAVIDRIO", "VIRGEN"): 5,
    ("FILLERS", "VIRGEN"): 2,
    ("FV", "COMPUESTO"): 5,
    ("FV", "R"): 5,
    ("FV", "VIRGEN"): 5,
    ("MolinoPE", None): 8,
    ("MolinoPP", None): 16,
    ("PC", "VIRGEN"): "no",
    ("PE", "F"): 7,
    ("PE", "R"): 8,
    ("PE", "VIRGEN"): 7,
    ("PE001", "MI02"): "no",
    ("PE001", "MI50"): "no",
    ("PE001", "NA"): "no",
    ("PE002", "MI08"): "no",
    ("PE003", "MI05"): "no",
    ("PE003", "MI06"): "no",
    ("PE004", "MAQUILA"): "no",
    ("PE004", "NA"): "no",
    ("PE006", "MOLIDOLIMPIO"): "no",
    ("PE011", "NA"): "no",
    ("PE_ADCOPO", "VIRGEN"): 6,
    ("PE_ADHOMO", "COMPUESTO"): 7,
    ("PE_ADHOMO", "FUERAGRADO"): 7,
    ("PE_ADHOMO", "MOLIDOLIMPIO"): 8,
    ("PE_ADHOMO", "MOLIDOSUCIO"): 8,
    ("PE_ADHOMO", "MOLIDOSUCIOCONTAMINADO"): 8,
    ("PE_ADHOMO", "REPROCESADO"): 8,
    ("PE_ADHOMO", "VIRGEN"): 7,
    ("PE_BDLINEAL", "FUERAGRADO"): 9,
    ("PE_LINEAL", "FUERAGRADO"): 9,
    ("PE_LINEAL", "REPROCESADO"): 9,
    ("PE_LINEAL", "VIRGEN"): 9,
    ("PE_MLLD", "REPROCESADO"): 9,
    ("PE_SOPLADO", "COMPUESTO"): "no",
    ("PE_SOPLADO", "REPROCESADO"): "no",
    ("PE_SOPLADO", "VIRGEN"): "no",
    ("PP", "F"): 15,
    ("PP", "R"): 16,
    ("PP", "VIRGEN"): 15,
    ("PP001", "MI00"): "no",
    ("PP001", "MI11"): "no",
    ("PP001", "MI12"): "no",
    ("PP001", "MI15"): "no",
    ("PP001", "MI20"): "no",
    ("PP001", "MI25"): "no",
    ("PP002", "IMPACTO"): "no",
    ("PP002", "MI35"): "no",
    ("PP003", "MI00"): "no",
    ("PP004", "MAQUILA"): "no",
    ("PP004", "NA"): "no",
    ("PP005", "NA"): "no",
    ("PP011", "MOLIDOLIMPIO"): "no",
    ("PP011", "PELETRAFIA"): "no",
    ("PP012", "TORTADEPPMOLIDA"): "no",
    ("PP015", "NA"): "no",
    ("PP017", None): "no",
    ("PP018", None): "no",
    ("PP019", None): "no",
    ("PPHOMO_COPO", "FUERAGRADO"): 15,
    ("PPHOMO_COPO", "REPROCESADO"): 16,
    ("PPHOMO_COPO", "WASHNDRY"): 16,
    ("PP_COIM", "FUERAGRADO"): 10,
    ("PP_COIM", "REPROCESADO"): 13,
    ("PP_COIM", "VIRGEN"): 10,
    ("PP_CONBRE", "FUERAGRADO"): 11,
    ("PP_CONBRE", "VIRGEN"): 11,
    ("PP_CORCLA", "FUERAGRADO"): 12,
    ("PP_CORCLA", "VIRGEN"): 12,
    ("PP_HOMO", "BARREDURA"): 16,
    ("PP_HOMO", "COMPUESTO"): 16,
    ("PP_HOMO", "FUERADEGRADO"): 15,
    ("PP_HOMO", "MOLIDOCONTAMINADOLAVADO"): 16,
    ("PP_HOMO", "MOLIDOLIMPIO"): 16,
    ("PP_HOMO", "MOLIDOSUCIO"): 16,
    ("PP_HOMO", "REPROCESADO"): 16,
    ("PP_HOMO", "VIRGEN"): 15,
    ("PP_HOMO", "WASHNDRY"): 16,
    ("PP_SOPLADO", "VIRGEN"): "no",
    ("PV", "R"): "no",
    ("PVC001", "NA"): "no",
    ("RebabaPP", None): "no",
    ("TE", "VIRGEN"): "no",
    ("TP", "R"): "no",
    ("TPE", "REPROCESADO"): 14,
    ("TPE", "VIRGEN"): 14,
    ("TPE_PVC", "REPROCESADO"): 14,
    ("TortaPE", None): 8,
    ("TortaPP", None): 16,
}

ITEM_GROUP_MAP = {
    (item_number, normalize_configuration(config_id)): group
    for (item_number, config_id), group in RAW_ITEM_GROUP_MAP.items()
}


def get_group(item_number, config_id):
    key = (item_number, normalize_configuration(config_id))
    if key not in ITEM_GROUP_MAP:
        return UNCLASSIFIED_KEY, UNCLASSIFIED
    group = ITEM_GROUP_MAP[key]
    if group == EXCLUDED:
        return EXCLUDED, None
    return group, GROUP_NAMES[group]
